### ISSUE TITLE
'molecule_to_molecule_name' referenced before assignment

### ISSUE THREAD

**Issue by harvey2phase** [Samuel-Buteau/universal-battery-database#35]
<img width="1546" alt="Screen Shot 2020-04-26 at 8 54 49 AM" src="https://user-images.githubusercontent.com/24196676/80307253-2bf0b800-879e-11ea-9a86-5b318a02a4d3.png">

**Comment by Samuel-Buteau** [comment]
I have fixed the problem:

When calling the code with/without name files, we are supposed to define an empty dictionary for all the names, and then, if a name file is provided, override the default with the given dictionary of names

the default assignment was missing
